// <auto-generated />
using System;
using EstoqueTIRDEB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EstoqueTIRDEB.Migrations
{
    [DbContext(typeof(EstoqueTIRDEBContext))]
    [Migration("20240218162712_CorrigindoEntidade")]
    partial class CorrigindoEntidade
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EstoqueTIRDEB.Models.EntradaEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataEntrada");

                    b.Property<int>("ItemId");

                    b.Property<int>("Quantidade");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("EntradaEstoque");
                });

            modelBuilder.Entity("EstoqueTIRDEB.Models.Itens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoriaId");

                    b.Property<DateTime>("DataAquisicao");

                    b.Property<string>("Especificações");

                    b.Property<string>("Modelo");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("EstoqueTIRDEB.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomeUsuario")
                        .IsRequired();

                    b.Property<string>("Senha")
                        .IsRequired();

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("EstoqueTIRDEB.Models.EntradaEstoque", b =>
                {
                    b.HasOne("EstoqueTIRDEB.Models.Itens", "Item")
                        .WithMany("EntradasEstoque")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
