// <auto-generated />
using System;
using EstoqueTIRDEB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EstoqueTIRDEB.Migrations
{
    [DbContext(typeof(EstoqueTIRDEBContext))]
    partial class EstoqueTIRDEBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EstoqueTIRDEB.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("EstoqueTIRDEB.Models.EntradaEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataEntrada");

                    b.Property<int>("ItemId");

                    b.Property<int>("Quantidade");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("EntradaEstoque");
                });

            modelBuilder.Entity("EstoqueTIRDEB.Models.Itens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CD");

                    b.Property<int>("CategoriaId");

                    b.Property<DateTime>("DataAquisicao");

                    b.Property<string>("DepartamentoSetor");

                    b.Property<string>("Equipamento");

                    b.Property<string>("Especificações");

                    b.Property<string>("Fabricante");

                    b.Property<string>("Hostname");

                    b.Property<string>("Modelo")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("NotaFiscal");

                    b.Property<string>("NumeroSerie");

                    b.Property<string>("Patrimonio");

                    b.Property<int>("Quantidade");

                    b.Property<string>("SistemaOperacional");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("EstoqueTIRDEB.Models.RetiradaEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataHoraRetirada");

                    b.Property<int>("ItemId");

                    b.Property<int>("QuantidadeRetirada");

                    b.HasKey("Id");

                    b.ToTable("RetiradaEstoque");
                });

            modelBuilder.Entity("EstoqueTIRDEB.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomeUsuario")
                        .IsRequired();

                    b.Property<string>("Senha")
                        .IsRequired();

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("EstoqueTIRDEB.Models.EntradaEstoque", b =>
                {
                    b.HasOne("EstoqueTIRDEB.Models.Itens", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EstoqueTIRDEB.Models.Itens", b =>
                {
                    b.HasOne("EstoqueTIRDEB.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
