// <auto-generated />
using System;
using EstoqueTIRDEB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EstoqueTIRDEB.Migrations
{
    [DbContext(typeof(EstoqueTIRDEBContext))]
    partial class EstoqueTIRDEBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EstoqueTIRDEB.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("EstoqueTIRDEB.Models.EntradaeSaida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int?>("ItensId");

                    b.Property<int>("Quantidade");

                    b.HasKey("Id");

                    b.HasIndex("ItensId");

                    b.ToTable("EntradaeSaidas");
                });

            modelBuilder.Entity("EstoqueTIRDEB.Models.Itens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CategoriaId");

                    b.Property<DateTime>("DataAquisicao");

                    b.Property<string>("Especificações");

                    b.Property<string>("Modelo");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("EstoqueTIRDEB.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomeUsuario")
                        .IsRequired();

                    b.Property<string>("Senha")
                        .IsRequired();

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("EstoqueTIRDEB.Models.EntradaeSaida", b =>
                {
                    b.HasOne("EstoqueTIRDEB.Models.Itens", "Itens")
                        .WithMany("EntradaeSaidas")
                        .HasForeignKey("ItensId");
                });

            modelBuilder.Entity("EstoqueTIRDEB.Models.Itens", b =>
                {
                    b.HasOne("EstoqueTIRDEB.Models.Categoria", "Categoria")
                        .WithMany("Iten")
                        .HasForeignKey("CategoriaId");
                });
#pragma warning restore 612, 618
        }
    }
}
